# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"

  lane :distribution do
    # add actions here: https://docs.fastlane.tools/actions
    # 增加build版本号
    # increment_build_number
    gym(
    	clean:true, #打包前clean项目
		scheme:"DdDd", #schema
		export_method:"app-store",  #导出方式
		configuration: "Distribution", #环境
		output_directory:"./build", #ipa的存放目录
		archive_path:"./Archive", 
		export_xcargs:"-allowProvisioningUpdates"
	)
  end
end
