# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"

  # 打App Store包
  desc '打App Store包'
  lane :appstore_ipa do
    # add actions here: https://docs.fastlane.tools/actions
    # 增加build版本号
    # increment_build_number

    # 导出方式
    export_method = "app-store"   

    # 导出路径
    output_directory = "../build/app-store/#{Time.now.strftime('%Y%m%H%M%S')}/"

    scheme_name = "DdDd"

    # 导出名称
    output_name = "#{scheme_name}_#{Time.now.strftime('%Y%m%H%M%S')}.ipa"
    gym(
    	clean:true, #打包前clean项目
		scheme:scheme_name,   #schema
		export_method: export_method,  #导出方式
		configuration: "Distribution", #环境
		output_directory:output_directory, #ipa的存放目录
		output_name: output_name, 
		archive_path:"#{output_directory}Archive",
		export_xcargs:"-allowProvisioningUpdates"
	)
  end
 
  # 打ad-hoc包
  desc '打ad-hoc包'
  lane :adhoc do

    # 导出方式
    export_method = "app-store"  

    scheme_name = "DdDd"
    # build_app是gym的别名,可以换成gym
    build_app(
        schema: scheme_name,
        export_method: export_method
    )

    # 上传到蒲公英
    #pgyer(api_key: "", user_key: "")
  end

  # 下载provisioning_profile
  desc '下载provisioning_profile'
  lane :adhoc_profile do
  end



  # 上传ipa到iTunesConnect，发布到App Store
  desc '上传ipa到iTunesConnect，发布到App Store'
  lane :deploy do 

    metadata_path = "./metadata"

    deliver(
        submit_for_review: false,
        force: true,
        ignore_language_directory_validation: true,
        metadata_path: metadata_path
        )
  end

  # 添加Devices到AppleDeveloper
  lane :add_device do
    register_devices(
        devices_file: "./devices.txt"
        )
  end

  # 生成截图
  lane :snap_shot do
  end

  # 生成不同尺寸的icon
  desc '生成不同尺寸的icon'
  lane :app_icon do

    puts '生成不同尺寸的icon'
    appiconfile = 'DdDd/DdDd/Assets/AppIcon.png'

    appiconpath = 'DdDd/DdDd/Assets/Assets.xcassets'
    appicon(
          appicon_image_file: appiconfile,
          appicon_devices: [:iphone, :ios_marketing],
          appicon_path: appiconpath
        )

  end

end
