platform :ios, '9.0'

inhibit_all_warnings!

workspace 'DdDd'

project 'DdDd/DdDd.xcodeproj'

target 'DdDd' do
  use_frameworks!
  
  
  # 布局
  pod 'SnapKit'
  pod 'IQKeyboardManagerSwift'
  
  # 流程
  pod 'RxSwift'
  
  # 网络
  pod 'RxCocoa'
  
  pod 'RxAlamofire'

  # 工具
  pod 'CryptoSwift'
  pod 'HandyJSON', '4.1.1'
  pod 'SQLite.swift', '~> 0.11.5'
  pod 'Toast-Swift', '~> 3.0.1'
  pod 'SVProgressHUD', '~> 2.2.5'
  pod 'SwiftMessages'
  pod 'CHIPageControl'
  pod 'Fabric'
  pod 'Crashlytics'

 # 日志
 pod 'XCGLogger'
  # Pods for OneMall
  #target 'OneMall_Tests' do
      #inherit! :search_paths
      
      #pod 'Quick', '~> 1.3.1'
      #pod 'Nimble', '~> 7.1.3'
      #pod 'FBSnapshotTestCase' , '~> 2.1.4'
      #pod 'Nimble-Snapshots' , '~> 6.7.1'
  #end
end
